#!/usr/bin/python3
import sys

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

def factorize_prime():
    try:
        with open(sys.argv[1]) as in_file:
            for num in in_file:
                num = int(num)
                if is_prime(num):
                    print("{}=1*{}".format(num, num))
                else:
                    if num % 2 == 0:
                        print("{}={}*{}".format(num, num // 2, 2))
                    else:
                        for i in range(3, int(num ** 0.5) + 1, 2):
                            if num % i == 0:
                                print("{}={}*{}".format(num, num // i, i))
                                break
                        else:
                            # If no prime factors were found, the number is prime
                            print("{}=1*{}".format(num, num))

    except (IndexError, ValueError):
        pass

if __name__ == "__main__":
    factorize_prime()

