#!/usr/bin/python3
 
import sys

def factorize_prime():
    try:
        with open(sys.argv[1]) as in_file:
            for num in in_file:
                num = int(num)
                if num % 2 == 0:
                        print("{}={}*{}".format(num, num // 2, 2))
                        continue
                i = 3
                while i < num // 2:
                    if num % i == 0:
                        print("{}={}*{}".format(num, num // i, i))
                        break
                    i = i + 2
                if i == (num // 2) + 1:
                    print("{}={}*{}".format(num, num, 1))
    except Exception as e:
        print(f"An error occurred: {e}")


factorize_prime()
