#!/usr/bin/python3
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

def prime_factorization(num):
    if is_prime(num):
        print("{}=1*{}".format(num, num))
    else:
        print("{} is not a prime number.".format(num))

if __name__ == "__main__":
    num = int(input("Enter a number: "))
    prime_factorization(num)

